- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
      tags:
        - hello-world

    - name: Show IP Address
      debug:
        msg: "{{ ansible_default_ipv4.address }}"
      tags:
        - ip-address
        
    - name: Ansible Jinja2 for range
      debug:
        msg: >
             --== Ansible Jinja2 for range

             {% for entry in range(1, 11) -%}
                {{ entry }}
             {% endfor %}
      tags:
        - jinja2
        
    - name: Ansible Jinja2 filters
      debug:
        msg: >
             ---=== Ansible Jinja2 filters ===---

             --== min [1, 2, 3, 4, 5] ==--

             {{ [1, 2, 3, 4, 5] | min }}

             --== max [1, 2, 3, 4, 5] ==--

             {{ [1, 2, 3, 4, 5] | max }}

             --== unique [1, 1, 2, 2, 3, 3, 4, 4, 5, 5] ==--

             {{ [1, 1, 2, 2, 3, 3, 4, 4, 5, 5] | unique }}

             --== difference [1, 2, 3, 4, 5] vs [2, 3, 4] ==--

             {{ [1, 2, 3, 4, 5] | difference([2, 3, 4]) }}

             --== random ['rob', 'jane', 'freddy'] ==--

             {{ ['rob', 'jane', 'freddy'] | random }}

             --== urlsplit hostname ==--

             {{ "http://docs.ansible.com/ansible/latest/playbooks_filters.html" | urlsplit('hostname') }}
      tags:
        - jinja2
        
    - name: Exploring register
      command: hostname -s
      when: 
        - ansible_distribution == "Ubuntu" 
        - ansible_distribution_major_version | int >= 16
      register: command_register
      tags:
        - register
        
    - name: Show register
      debug:
        var: command_register
      tags:
        - register
