- name: include import playbook
  host: all
  tasks:

     - name: Play 1 - Task 1
       debug: 
         msg: Play 1 - Task 1

     - include_tasks: play1_task2.yml

     - import_tasks: play1_task3.yml
 
- import_playbook: play2.yml
