-

  # Target: where our play will run and options it will run with
  hosts: all

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:

     - name: Play 2 - Task 1
       debug: 
         msg: Play 2 - Task 1

     - include_tasks: play2_task2.yml

